// Mock Tasks
export const mockTasks = [
  {
    id: '1',
    title: 'Complete project documentation',
    description: 'Write comprehensive documentation for the new feature',
    status: 'in-progress',
    priority: 'high',
    assignee: 'John Doe',
    dueDate: '2024-04-15',
  },
  {
    id: '2',
    title: 'Review code changes',
    description: 'Review pull requests for the new feature',
    status: 'todo',
    priority: 'medium',
    assignee: 'Jane Smith',
    dueDate: '2024-04-16',
  },
  {
    id: '3',
    title: 'Update test cases',
    description: 'Add new test cases for the feature',
    status: 'done',
    priority: 'low',
    assignee: 'John Doe',
    dueDate: '2024-04-14',
  },
];

// Mock Projects
export const mockProjects = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Modernize company website with new branding',
    status: 'in-progress',
    startDate: new Date('2023-01-15'),
    endDate: new Date('2023-06-30'),
    manager: 'Jane Smith',
    budget: 75000,
    budgetSpent: 45000,
    progress: 60,
    risks: [],
    tasks: [],
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Create a mobile app for customer engagement',
    status: 'planned',
    startDate: new Date('2023-07-01'),
    endDate: new Date('2023-12-31'),
    manager: 'John Doe',
    budget: 120000,
    budgetSpent: 0,
    progress: 0,
    risks: [],
    tasks: [],
  },
];

// Mock Risks
export const mockRisks = [
  {
    id: '1',
    title: 'Budget Overrun',
    description: 'Project expenses exceed allocated budget',
    impact: 'high',
    likelihood: 'medium',
    status: 'mitigating',
    category: 'Financial',
    projectId: '1',
    projectName: 'Website Redesign',
    owner: 'Finance Team',
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2023-03-15'),
  },
  {
    id: '2',
    title: 'Resource Shortage',
    description: 'Insufficient developer resources to meet timeline',
    impact: 'medium',
    likelihood: 'high',
    status: 'identified',
    category: 'Resource',
    projectId: '1',
    projectName: 'Website Redesign',
    owner: 'Project Manager',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2023-02-15'),
  },
];

// Mock Assets
export const mockAssets = [
  {
    id: '1',
    name: 'MacBook Pro 16"',
    type: 'laptop',
    serialNumber: 'MP123456789',
    assignedTo: 'John Smith',
    department: 'Engineering',
    purchaseDate: new Date('2022-06-15'),
    warrantyExpiry: new Date('2025-06-15'),
    status: 'active',
    notes: '16GB RAM, 1TB SSD',
  },
  {
    id: '2',
    name: 'iPhone 14 Pro',
    type: 'mobile',
    serialNumber: 'IP987654321',
    assignedTo: 'Jane Doe',
    department: 'Marketing',
    purchaseDate: new Date('2022-09-20'),
    warrantyExpiry: new Date('2024-09-20'),
    status: 'active',
    notes: '256GB, Graphite',
  },
  {
    id: '3',
    name: 'Adobe Creative Cloud License',
    type: 'software',
    serialNumber: 'AC123456',
    assignedTo: 'Design Team',
    department: 'Design',
    purchaseDate: new Date('2023-01-10'),
    warrantyExpiry: new Date('2024-01-10'),
    status: 'active',
    notes: 'Annual subscription',
  },
]; 